### ISSUE TITLE
End-Type Controller

### ISSUE THREAD

**Issue by hodlboy** [CadworkMontreal/cwapi3d#1]
How can I use the end-type controller? I found it in the docs, but unfortunately not in the code.

**Comment by jspaquet** [comment]
The endtype_controller works with endtype IDs. You can get the ID from an endtype name via get_endtype_id (you can also do the reverse with get_endtype_name). This will only work for endtypes which are stored in the 3D file.

Once you have an ID you can use:

- get_endtype_id_start
- get_endtype_id_end
- get_endtype_id_facet
- get_endtype_name_start
- get_endtype_name_end
- get_endtype_name_facet
- set_endtype_name_start
- set_endtype_name_end
- set_endtype_name_facet
- set_endtype_id_start
- set_endtype_id_end
- set_endtype_id_facet

which work in a similar way to other getters and/or setters in CwAPI3D. For getter you pass an element and for setters you pass an element list and either the endtype ID or the name.
